Added vector Dirichlet and curved Hessian functionality
libigl/libigl pull request #1560
Opened 2020-07-05 00:15 UTC by odedstein

Added functions to compute the vector Dirichlet energy (as described [here](http://www.cs.columbia.edu/cg/a-simple-discretization/)) as well as the curved Hessian energy (as described [here](http://www.cs.columbia.edu/cg/curved-hessian/)).

Modified the smoothing tutorial to include new examples for the curved Hessian energy, and added two new tutorials for the vector Dirichlet energy. There will be a corresponding pull request to libigl.github.io with the tutorial updates.

There are unit tests for some of the new functions included.

#### Check all that apply (change to `[x]`)
- [x] All changes meet [libigl style-guidelines](https://libigl.github.io/style-guidelines/).
- [x] Adds new .cpp file.
- [x] Adds corresponding unit test.
- [ ] This is a minor change.

2020-09-08 01:27 UTC, jdumas requested changes
Thanks @odedstein for this contribution! This is really cool =). Would you be able to update the tutorial entries in the website once this is merged? It's a shame that we let PR sit around for so long, sorry about that...

Regarding your PR, the code looks pretty clean. There are a couple of minor issues I want to point out:
- You're using `int` explicitly in a couple of places. The code will likely not work on large meshes using 64 bit face indices.
- Please use braces! You have a habit of putting line-breaks in long one-line statement within a for/if, this almost gave me a heart attack.
- Do not use `const_cast` to add constness to a pointer/reference, this is not needed.

2020-09-08 01:27 UTC, jdumas commented on include/igl/cr_vector_laplacian.cpp
> +    const_cast<const Eigen::PlainObjectBase<DerivedE>& >(E),
`const_cast` is not needed to add constness, only to remove it. You can use the following instead:
```cpp
const Eigen::PlainObjectBase<DerivedE>& E_cst(E);
const Eigen::PlainObjectBase<DerivedOE>& oE_cst(oE);
cr_vector_laplacian(E_cst, oE_cst, L);
```

2020-09-08 01:27 UTC, jdumas commented on include/igl/cr_vector_laplacian.cpp
> +  const int m = F.rows();
`Eigen::Index` (64bit) rather than `int` (32bit) ?

2020-09-08 01:27 UTC, jdumas commented on include/igl/cr_vector_mass.cpp
> +      const int v1=F(f,(e+1)%3), v2=F(f,(e+2)%3);
Don't assume `int`, type should be `auto` or `DerivedF::Scalar`.

2020-09-08 01:27 UTC, jdumas commented on include/igl/cr_vector_curvature_correction.cpp
> +  for(int f=0; f<m; ++f) {
Don't assume `int`.

2020-09-08 01:27 UTC, jdumas commented on include/igl/cr_vector_curvature_correction.cpp
> +    for(auto v : loop)
Add braces around code.

2020-09-08 01:27 UTC, jdumas commented on include/igl/cr_vector_curvature_correction.cpp
> +igl::cr_vector_curvature_correction(
So we already have `crouzeix_raviart_massmatrix` and `crouzeix_raviart_cotmatrix`. I guess you want to abbreviate that into `cr_` to keep name shorter, but I just want to make sure we're all ok with introducing an inconsistency here?

2020-09-08 01:27 UTC, jdumas commented on include/igl/curved_hessian_energy.cpp
> +      it; ++it)
Oh gosh please add braces.

2020-09-08 01:27 UTC, jdumas commented on include/igl/curved_hessian_energy.cpp
> +  for(int k=0; k<M.outerSize(); ++k)
Don't assume `int`

2020-09-08 01:27 UTC, jdumas commented on include/igl/orient_halfedges.cpp
> +  for(int f=0; f<m; ++f) {
`int`

2020-09-08 01:27 UTC, jdumas commented on include/igl/edge_vectors.h
> +template<bool computePerpendicular=true,
I didn't realize giving default value for the *first* template parameters works (I would expect only the last params can be default-valued).

2020-09-08 01:27 UTC, jdumas commented on include/igl/edge_vectors.cpp
> +      if(computePerpendicular) //This should ideally be an if constexpr
omg please use braces here.

2020-09-08 01:27 UTC, jdumas commented on include/igl/edge_vectors.cpp
> +  const int m = E.maxCoeff()+1;
`int`

2020-09-08 01:27 UTC, jdumas commented on tests/include/igl/cr_vector_curvature_correction.cpp
> +  Kexact << 2.09439510239319,-0.370240244846531,0,0,0.370240244846531,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-0.370240244846531,0,0,-0.370240244846531,0,-5.55111512312578e-17,-5.55111512312578e-17,0,0,0,0,0,0,0
FYI, if you need to enter binary data in C++ code, you can dump it with `std::cout << std::hexfloat` first (that would avoid conversion to base 10 and back).

2020-09-08 01:27 UTC, jdumas commented on tests/include/igl/cr_vector_curvature_correction.cpp
> +  std::vector<double> initvec = {0.175872799393935,0.0527294359766379,0,0,0.0639602308808338,0,-0.00532268422271531,0,-0.000417793718813767,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Should this be part of https://github.com/libigl/libigl-tests-data ? Seems rather lengthy.

2020-09-12 18:47 UTC, odedstein commented
Thanks for the feedback. I'm a bit busy at the moment, but I will look at your requested changes and apply them as soon as I have time. The changes all look sensible and doable.

I have a small question about your suggested fix to avoid the const cast. Can you explain this fix in a bit more detail? Does it avoid allocation / calling a constructor?

I do not know if it makes much sense to add a function
`cr_vector_laplacian(
    const Eigen::MatrixBase<DerivedV>& V,
    const Eigen::MatrixBase<DerivedF>& F,
    Eigen::SparseMatrix<ScalarL>& L);`
that does not also return `E` and `oE`, since the indices of the entries of `L` depend on the edge numbering and edge orientation chosen (which can not be inferred from `V,F` alone), and results of computations with `L` are hard to interpret without knowing which index is which edge.

I have made updates to the libigl website tutorials as well (https://github.com/odedstein/libigl.github.io), although I think the tutorials have been changed since, so this might be out of date.

Thanks again!

2020-09-12 19:35 UTC, jdumas commented
> I have a small question about your suggested fix to avoid the const cast. Can you explain this fix in a bit more detail? Does it avoid allocation / calling a constructor?

So, the `const_cast` is not needed to "add" const-ness to a `&` or `*`, since you can use implicit type conversion instead. E.g. calling if you have a function `void foo(const int *p)`, then calling `foo(ptr)` on a `int * ptr` will work out of the box, without any need for const-cast. In this case, due to overload/templating you need to call `foo(x)` on an input with the correct type, otherwise the compiler will not be able to deduce and will complain. So to avoid `const_cast`, you simply need to go through an intermediate temporary variable of the right type. You can use `const auto &x(y)` to convert `y` into a const version of itself. Note that `const_cast` can have other [unintended side-effects](https://stackoverflow.com/questions/20956757/using-const-cast-to-add-const-ness-bad-idea) so it a good habit to avoid it if you can.

If your temporary variable is `&` or `*`, then no copy/allocation is performed (it's just a pointer).

> I do not know if it makes much sense to add a function
cr_vector_laplacian( const Eigen::MatrixBase<DerivedV>& V, const Eigen::MatrixBase<DerivedF>& F, Eigen::SparseMatrix<ScalarL>& L);
that does not also return E and oE, since the indices of the entries of L depend on the edge numbering and edge orientation chosen (which can not be inferred from V,F alone), and results of computations with L are hard to interpret without knowing which index is which edge.

I guess I just found it a bit odd to have an argument marketed as "input" that is "computed if not provided". But now that you explain it it's probably fine. Maybe it should be documented as an "output" of the function in the second signature.

> I have made updates to the libigl website tutorials as well (https://github.com/odedstein/libigl.github.io), although I think the tutorials have been changed since, so this might be out of date.

Cool!

2020-09-21 18:39 UTC, odedstein commented
Hi,
I have applied the changes you have suggested.
I would be glad if you could look at the tutorials I changed / added (712, 721, 722). I currently only have access to a Mac machine, so I can't be sure if they look correct on Windows / Linux.

2020-09-21 18:45 UTC, jdumas commented
Hmm could you also merge your branch with the current master branch? The PR currently shows about ~200 file changed, so that looks a bit suspicious.

2020-09-21 18:48 UTC, odedstein commented
> Hmm could you also merge your branch with the current master branch? The PR currently shows about ~200 file changed, so that looks a bit suspicious.

Wow... I have no idea what just happened. I merged libigl, but I must have merged the wrong thing. Sorry for that.

2020-09-21 19:07 UTC, odedstein commented
Now it only says 32 files changed, which looks correct, however now all my noisy commit messages that I made during work on your review are present, sorry...

2020-09-21 19:14 UTC, jdumas commented
No worries, we can squash them upon merging. I'll take a look a the tutorials on my linux when I get the chance.

2020-09-27 03:06 UTC, jdumas approved these changes
Alright, tested the tutorials on macOS and Linux, they look great. Thanks for your contribution @odedstein ! Let me know when you get the chance to update the website and make a PR accordingly!

2020-09-27 03:06 UTC, merged